### ISSUE TITLE
Default window width causes horizontal scrollbar

### ISSUE THREAD

**Issue by Trippnology** [RocketManRC/JS8Assistant#2]
The default window width is just a few pixels too narrow to fit the table width. This looks like a difference between Mac and Windows.

![JS8A-scrollbars](https://user-images.githubusercontent.com/846436/122459361-c1ee3000-cfa8-11eb-9dc3-8fe8db5f49f4.png)

You can of course drag the window a little wider and the scrollbar goes away. I can't tell exactly, but 10-15 pixels extra should be enough to get rid of this.

**Comment by RocketManRC** [comment]
I can believe I didn't notice that! It needed 17 more pixels width and fixed now in version 0.21.1
